### ISSUE TITLE
Error while generating brightness temperature maps

### ISSUE THREAD

**Issue by aishrimc** [andreimesinger/21cmFAST#16]
I am trying to generate Tb maps using the default parameters at redshift 9. In the step `./find_HII_bubbles <redshift> [<previous redshift>]`
, I have set the 'previous redshift' as 30, and this step generates a xH file named 
' ** xH_nohalos_z009.00_nf0.749270_Fstar0.0500_starPL0.5000_Fesc0.1000_escPL-0.5000_Mturn5.00e+08_HIIfilter1_RHIImax50_200_300Mpc** '. After this in the step
 `./delta_T 9 ../Boxes/xH_nohalos_z009.00_nf0.749270_Fstar0.0500_starPL0.5000_Fesc0.1000_escPL-0.5000_Mturn5.00e+08_HIIfilter1_RHIImax50_200_300Mpc`
 I am getting the error message :
`delta_T: threading with default 2 threads
mkdir: cannot create directory ‘../Log_files’: File exists
mkdir: cannot create directory ‘../Output_files/’: File exists
mkdir: cannot create directory ‘../Log_files’: File exists
Reading in xH box
Reading in deltax box
delta_T.c: Error openning Ts file (null) to read from
Aborting...
`

Please let me know what I am doing wrong here.

**Comment by andreimesinger** [comment]
If you want to compute the spin temperature, you need to make sure that the Ts.c code is called at the corresponding redshift.  If you do not, then you should turn off the option USE_TS_IN_21CM in HEAT_PARAMS.H.

I recommend using the drivers provided to avoid such issues.
