### ISSUE TITLE
can you make a release?

### ISSUE THREAD

**Issue by gijzelaerr** [andreimesinger/21cmFAST#2]
hi! 

It has been requested that this software becomes part of the KERN suite:

http://kernsuite.info

see packaging discussion here:

https://github.com/kernsuite/packaging/issues/21

For this I will try to make a package of this software. Can you maybe press the 'make release' button? That would simplify my packaging life.

Thanks!

**Comment by andreimesinger** [comment]
Hi,
I do not see a 'make release' button...  Could you please be more specific (apologies, but I am a newcomer to github).
Thanks.

**Comment by gijzelaerr** [comment]
on this page

https://github.com/andreimesinger/21cmFAST/releases

![screen shot 2017-01-23 at 11 40 59](https://cloud.githubusercontent.com/assets/326308/22198805/dad0bf56-e160-11e6-8fe7-a0c9916830bb.png)

thanks!

**Comment by andreimesinger** [comment]
ok, i have done this.  thanks.

**Comment by gijzelaerr** [comment]
a package is now available in kern-1 and kern-dev
