### ISSUE TITLE
if(USE_HALO_FIELD) in if(!USE_HALO_FIELD)

### ISSUE THREAD

**Issue by qyx268** [andreimesinger/21cmFAST#7]
Programs/find_HII_bubbles.c   -- Line 708 - 757
in if (!USE_HALO_FIELD){...} there is a check of USE_HALO_FIELD, which will always be passed. 

Please check if it's a bug.

**Comment by andreimesinger** [comment]
fixed.  i am now checking if the halo finding version works, since we never use it for the 21cm fields.  i will push new version afterwards
